id: P000435
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:39:48.084462
source_metadata:
  id: bdr:W20390
  title: བྱང་ཆུབ་སེམས་དཔའ་རྟག་ངུའི་རྟོགས་བརྗོད་སྙན་དངགས་དཔག་བསམ་གྱི་ལྗོན་པ
  author: ''
  volumes:
    66ea9e7b70fe42e18e046dc90506c507:
      image_group_id: I4701
      title: ''
      volume_number: 1
      total_pages: 310
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
